# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bdb15cfa7c7012ae784c205abc15f90cfd6f32a87108efd0bd94a2e9e9156438d3d9c2da925da5fafdbc4a2a4f34a0d56159fd3792beb48361e53125f1f88f8

test:
  secret_key_base: 8981138e430706ac1df61096160baf90d18c767f3da8c6243480de5b9482c61620dac69c66eaeef8d0852bb3944f51ba6752cdc9061c3b5d45099b815e53f643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
